config/routes.rb
TekApp::Application.routes.draw do
  resources :notifications do
    member do
      post 'push'
    end
  end

  resources :users

  resources :sessions

  root 'welcome#index'
  
  get 'hello_self', to: 'welcome#hello_self'

  get 'login', to: redirect('/auth/google')
  get 'logout', to: 'sessions#destroy'
  
  get '/auth/failure', to: 'sessions#failure'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  
  before_create :generate_key
  
  def generate_key
    self.key = SecureRandom.uuid
  end
  
  def self.from_param(key)
    find_by_key(key)
  end
  
  def to_param
    self.key
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  protect_from_forgery :except => [:push]
  
  before_filter :login_required!, except: [:push]
  
  def index
    @notifications = Notification.where(user_id: current_user.id)
  end
  
  def push
    @notification = Notification.from_param(params[:id])
    resp = Timeline.create(@notification.user, @notification.message)
    
    respond_to do |format|
      format.html {
        if resp.ok?
          flash[:success] = 'Notificaiton sent'
        else
          flash[:danger] = "Error while sending notification: #{Timeline.error}"
        end
      }
      format.json {
        render json: { success: resp.ok? }
      }
      format.xml {
        render xml: { success: resp.ok? }
      }
    end
  rescue NoGoogleApiTokenError => e
    flash[:warning] = "Could not find a valid mirror api token #{e}"
    redirect_to '/'
  rescue InvalidRequestError => e
    flash[:warning] = "Error performing request, #{e.message}"
    redirect_to '/'
  rescue NotAuthenticatedError => e
    logger.info e.inspect
    flash[:danger] = "Mirror api token is not authorized or has expired"
    redirect_to '/'
  rescue UnknownRequestError => e
    flash[:warning] = "Error performing request, #{e.message}"
    redirect_to '/'        
  end
  
  def new
    @notification = Notification.new
  end
  
  def create
    @notification = current_user.notifications.build(notification_params)
    
    respond_to do |format|
      if @notification.save
        format.html {
          flash[:success] = "New notification created"
          redirect_to @notification
        }
      else
        format.html {
          render :new
        }
      end
    end
  end
  
  def edit
    @notification = current_user.notifications.from_param(params[:id])
  end
  
  def update
    @notification = current_user.notifications.from_param(params[:id])
    respond_to do |format|
      if @notification.update_attributes(notification_params)
        format.html {
          flash[:success] = "Updated notification"
          redirect_to @notification
        }
      else
        format.html {
          render :edit
        }
      end
    end
  end
  
  def show
    @notification = current_user.notifications.from_param(params[:id])
  end
  
  def destroy
    @notification = current_user.notifications.from_param(params[:id])
    
    respond_to do |format|
      if @notification.destroy
        flash[:success] = "Notification deleted"
      else
        flash[:danger] = "Unable to delete the notification"          
      end
      
      format.html {
        redirect_to notifications_path
      }
    end
  end
  
  protected
  
  def notification_params
    params.require(:notification).permit(:name, :message)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
- unless @notification.errors.empty?
  .alert.alert-danger
    %h3 Error saving notification
    %ul
      - @notification.errors.full_messages.each do |msg|
        %li= msg
= form_for @notification do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-3'
    .col-lg-9
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :message, class: 'control-label col-lg-3'
    .col-lg-9
      = f.text_area :message, rows: 10, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-primary pull-right'

app/views/notifications/_notification.html.haml
%tr
  %td= notification.name
  %td= notification.message
  %td
    .btn-group
      = link_to 'View', notification, class: 'btn btn-default'
      = link_to 'Edit', edit_notification_path(notification), class: 'btn btn-default'
      = link_to 'Destroy', notification_path(notification), method: :delete, prompt: 'Are you sure?', class: 'btn btn-danger'
    

app/views/notifications/edit.html.haml
%h1 Edit notification
= render 'form'

app/views/notifications/index.html.haml
%table.table
  %legend 
    Notifications
    .pull-right
      = link_to 'New Notification', new_notification_path, class: 'btn btn-success'
  %thead
    %tr
      %th Name
      %th Message
      %th Actions
  %tbody
    = render @notifications

app/views/notifications/new.html.haml
%h1 New notification
= render 'form'

app/views/notifications/push.html.haml
%h1 Sent notification!

app/views/notifications/send.html.haml
%h1 Sent notification!

app/views/notifications/show.html.haml
%dl.dl-horizontal
  %dt Name
  %dd= @notification.name
  %dt Message
  %dd= @notification.message
  %dt Key
  %dd= @notification.key
  
.panel.panel-info
  .panel-heading
    Notification instructions
  .panel-body
    %dl
      %dt Url for to use for notifcation: 
      %dd
        [POST]
        = push_notification_url(@notification)
      %dt &nbsp;
      %dd
        = link_to 'Test', push_notification_url(@notification), method: :post, class: 'btn btn-default'
= link_to 'Back', notifications_path, class: 'btn btn-default'